import cabbage from "./resources/images/items/cabbage.png";
import orange from "./resources/images/items/orange.png";
import apple from "./resources/images/items/apple.png";
import avocado from "./resources/images/items/avocado.png";
import banana from "./resources/images/items/banana.png";
import eggplant from "./resources/images/items/eggplant.png";
import kirsche from "./resources/images/items/kirsche.png";
import kiwi from "./resources/images/items/kiwi.png";
import limetten from "./resources/images/items/limetten.png";
import watermelone from "./resources/images/items/watermelone.png";

const dummyData = [
  {
    id: 1,
    title: "Apfel Rot",
    ArtikelNr: 111,
    img: apple,
    type: "Conventionel",
    productForm: "fruit",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 2,
    title: "Weiß Kohl",
    ArtikelNr: 630,
    img: cabbage,
    type: "Conventionel",
    productForm: "vegetable",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 3,
    title: "Aubergine",
    ArtikelNr: 9172,
    img: eggplant,
    type: "Bio",
    productForm: "vegetable",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 4,
    title: "Wassermelone",
    ArtikelNr: 450,
    img: watermelone,
    type: "Conventionel",
    productForm: "fruit",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 5,
    title: "Orange",
    ArtikelNr: 9483,
    img: orange,
    type: "Bio",
    productForm: "fruit",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 6,
    title: "Avocado",
    ArtikelNr: 9166,
    img: avocado,
    type: "Bio",
    productForm: "fruit",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 7,
    title: "Banane",
    ArtikelNr: 9173,
    img: banana,
    type: "Bio-Demeter",
    productForm: "fruit",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 8,
    title: "Kirsche",
    ArtikelNr: 401,
    img: kirsche,
    type: "Conventionel",
    productForm: "fruit",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 9,
    title: "Kiwi",
    ArtikelNr: 9402,
    img: kiwi,
    type: "Bio",
    productForm: "fruit",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 10,
    title: "Limette",
    ArtikelNr: 422,
    img: limetten,
    type: "Conventionel",
    productForm: "vegetable",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 11,
    title: "Rindergulash",
    ArtikelNr: 4321,
    img: "https://lh3.googleusercontent.com/proxy/Zm4jjkhk4yEbfHrL0DfCTULVCJ36AUfVofUJjSBmOVmHD25qctTX01zc9Z_aYBappBnpXb-S9FKVwIMIE-RsOW1TFSQ4_orRe-d7HGM7",
    type: "Conventionel",
    productForm: "meat",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 12,
    title: "Speck",
    ArtikelNr: 4311,
    img: "https://www.pursuedtirol.com/media/image/39/04/60/Speck_Viertel_ecke_schmidspeck_bild1.png",
    type: "Conventionel",
    productForm: "meat",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 13,
    title: "Brötchen",
    ArtikelNr: 8215,
    img: "https://www.kondiback.de/medien/extensions/galerie_tooltip/13330ef3c9_0_1200_857.png",
    type: "Conventionel",
    productForm: "bread",
    isLearned: false,
    isAnswered: false,
  },
  {
    id: 14,
    title: "Dunkel Donut",
    ArtikelNr: 8115,
    img: "https://e7.pngegg.com/pngimages/675/1011/png-clipart-doughnut-lollipop-donut-food-donut-png.png",
    type: "Conventionel",
    productForm: "bread",
    isLearned: false,
    isAnswered: false,
  },
];

export default dummyData;
